import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StepProgressBarUnit from "@/components/StepProgressBarUnit";
import StepProgressBar from "@/components/StepProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-20 bg-green-500 w-fit  m-auto">
        <section className="grid grid-cols-2 ">
          <div className="">step progreess bar
          <StepProgressBar/>
          </div>
          <div className="bg-white">{children}</div>
        </section>
        </main>
      </body>
    </html>
  );
}
